version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production  # режим ПРОДакшена
    networks:
      - app_network
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
